### PR TITLE
Merging changes from test to the production branch

### PR DESCRIPTION
**Pull request by claytonkristiansen**
Completing sprint 3 with a pull request to the production level app.

### CODE REVIEW

**Review by Feng-Justin — APPROVED** [review]
All looks good, there are tests and the code passes the tests

**Review by alexnelsontamu — APPROVED** [review]
Looks good. The checks pass and coding style follows our set standards

**Review by JenniFeier — APPROVED** [review]
Looks good, coding style is consistent, all tests passed.

**Comment by erntv** [comment]
Looks good. All checks pass and consistent. Good work everyone.

**Review by erntv — APPROVED** [review]
Looks good. See prev comment.

**Pull request merged**
